spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sahagu_fieldwork
    username: sahagu_admin
    password: sahagu_local_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081