spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sahagu_fieldwork
    username: sahagu_admin
    password: sahagu_local_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

kakao:
  rest-api-key: a45c17219e0605be0389a46884cd5dd3

ors:
  api-key: eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjU0NjI0NWU2NTQ3YTRjMTI5NTQ5YTFjZjNlNmQ1N2E5IiwiaCI6Im11cm11cjY0In=
