import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { showAlert } from '../components/CustomAlert';
import { EmptyState, ScreenHeader, SectionTitle } from '../components/ui';
import { groupApi } from '../utils/groupApi';
import { colors, radius } from '../constants/design';

const isPersonal = (group) => Boolean(group?.personalWorkspace || group?.personal || group?.workspaceType === 'PERSONAL');

export default function GroupScreen({ user, activeGroup, onBack, onCreate, onInvitations, onOpenGroup }) {
  const [groups, setGroups] = useState([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false);
  const load = useCallback(async () => { if (!user?.userId) return; try { const data = await groupApi(`/api/groups/user/${user.userId}`); setGroups(Array.isArray(data) ? data : []); } catch (error) { showAlert('그룹 조회 실패', error.message); } finally { setLoading(false); setRefreshing(false); } }, [user?.userId]);
  useEffect(() => { load(); }, [load]);
  return <View style={styles.container}>
    <ScreenHeader title="그룹" subtitle="업무공간을 선택하고 관리합니다" onBack={onBack} />
    <ScrollView contentContainerStyle={styles.body} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); load(); }} tintColor={colors.primary} />}>
      <View style={styles.actionRow}><Action icon="add" title="새 그룹" subtitle="팀 만들기" onPress={onCreate} /><Action icon="mail-outline" title="받은 초대" subtitle="초대 확인" onPress={onInvitations} /></View>
      <View style={styles.activeCard}><View style={styles.activeIcon}><Ionicons name="briefcase" size={22} color="#FFFFFF" /></View><View style={{ flex: 1 }}><Text style={styles.activeLabel}>현재 업무공간</Text><Text style={styles.activeName}>{isPersonal(activeGroup) ? `나 · ${activeGroup?.groupName}` : activeGroup?.groupName || '선택된 그룹 없음'}</Text><View style={styles.activeMeta}><Ionicons name="location" size={14} color={colors.primary} /><Text style={styles.activeMetaText}>{activeGroup?.regionSido || '부산광역시'}{activeGroup?.regionSigungu ? ` · ${activeGroup.regionSigungu}` : ''}</Text></View></View><Ionicons name="checkmark-circle" size={24} color={colors.primary} /></View>
      <SectionTitle title="내 업무공간" />
      {loading ? <ActivityIndicator color={colors.primary} style={{ marginTop: 30 }} /> : !groups.length ? <EmptyState icon="people-outline" title="가입한 그룹이 없습니다" description="새 그룹을 만들거나 받은 초대를 확인하세요." /> : groups.map((group) => { const personal = isPersonal(group); const selected = Number(activeGroup?.groupId) === Number(group.groupId); return <TouchableOpacity key={group.groupId} style={[styles.groupCard, selected && styles.groupCardActive]} onPress={() => onOpenGroup?.(group)} activeOpacity={0.78}><View style={[styles.groupIcon, personal && styles.personalIcon]}><Ionicons name={personal ? 'person-outline' : 'people-outline'} size={21} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.groupName}>{personal ? `나 · ${group.groupName}` : group.groupName}</Text><Text style={styles.groupMeta}>{personal ? '개인 업무공간' : `${group.memberCount || 1}명 · ${group.regionSigungu || '활동지역 미설정'}`}</Text></View>{selected ? <View style={styles.selectedBadge}><Text style={styles.selectedText}>사용 중</Text></View> : null}<Ionicons name="chevron-forward" size={18} color={colors.textFaint} /></TouchableOpacity>; })}
    </ScrollView>
  </View>;
}
function Action({ icon, title, subtitle, onPress }) { return <TouchableOpacity style={styles.action} onPress={onPress}><View style={styles.actionIcon}><Ionicons name={icon} size={21} color={colors.primary} /></View><View><Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionSub}>{subtitle}</Text></View></TouchableOpacity>; }
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background }, body: { padding: 20, paddingBottom: 34 },
  actionRow: { flexDirection: 'row', gap: 10, marginBottom: 14 }, action: { flex: 1, minHeight: 76, padding: 13, borderRadius: radius.medium, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 10 }, actionIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, actionTitle: { color: colors.text, fontSize: 13, fontWeight: '900' }, actionSub: { color: colors.textSoft, fontSize: 10, marginTop: 3 },
  activeCard: { backgroundColor: colors.surface, borderRadius: radius.large, borderWidth: 1.5, borderColor: '#BBD5F6', padding: 16, marginBottom: 26, flexDirection: 'row', alignItems: 'center', gap: 12, shadowColor: '#2466B5', shadowOpacity: 0.10, shadowRadius: 15, shadowOffset: { width: 0, height: 7 }, elevation: 4 }, activeIcon: { width: 48, height: 48, borderRadius: 15, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, activeLabel: { color: colors.textSoft, fontSize: 10, fontWeight: '800' }, activeName: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 4 }, activeMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 7 }, activeMetaText: { color: colors.primary, fontSize: 10.5, fontWeight: '700' },
  groupCard: { minHeight: 76, borderRadius: radius.medium, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, padding: 13, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 11 }, groupCardActive: { borderColor: colors.primary, backgroundColor: '#F3F8FF' }, groupIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, personalIcon: { backgroundColor: colors.blueSoft }, groupName: { color: colors.text, fontSize: 14, fontWeight: '900' }, groupMeta: { color: colors.textSoft, fontSize: 10, marginTop: 4 }, selectedBadge: { backgroundColor: colors.primarySoft, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5 }, selectedText: { color: colors.primary, fontSize: 9, fontWeight: '900' },
});
