import React, { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { WebView } from 'react-native-webview';
import { showAlert } from '../components/CustomAlert';
import { EmptyState, PrimaryButton, ScreenHeader } from '../components/ui';
import { colors, radius } from '../constants/design';

const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL;
const KAKAO_KEY = process.env.EXPO_PUBLIC_KAKAO_JAVASCRIPT_KEY || '';
const CATEGORIES = [{ key: 'tree', label: '가로수', icon: 'leaf-outline' }, { key: 'manhole', label: '맨홀뚜껑', icon: 'disc-outline' }, { key: 'bus', label: '버스정류장', icon: 'bus-outline' }];
const safeJson = (value) => JSON.stringify(value).replace(/</g, '\\u003c');
const featureName = (feature) => feature?.properties?.adm_nm || feature?.properties?.adm_name || feature?.properties?.name || '행정동';
const mockItems = (dong, category) => Array.from({ length: 4 }, (_, index) => ({ id: `${category}-${dong}-${index + 1}`, name: `${dong} ${CATEGORIES.find((item) => item.key === category)?.label || '시설'} ${index + 1}`, address: `부산광역시 사하구 ${dong} 현장 ${index + 1}` }));

function mapHtml(boundaries) { return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no"><style>html,body,#map{width:100%;height:100%;margin:0}.label{padding:4px 7px;background:#fff;border:1px solid #DCE7F5;border-radius:8px;font-size:10px;font-weight:700;color:#10285B;box-shadow:0 2px 8px rgba(0,0,0,.12)}</style><script src="https://dapi.kakao.com/v2/maps/sdk.js?appkey=${KAKAO_KEY}&autoload=false"></script></head><body><div id="map"></div><script>const data=${safeJson(boundaries)};kakao.maps.load(function(){const map=new kakao.maps.Map(document.getElementById('map'),{center:new kakao.maps.LatLng(35.103,128.975),level:7});let selected=null,hasAny=false;const allBounds=new kakao.maps.LatLngBounds();function ringsOf(g){return g.type==='Polygon'?[g.coordinates]:(g.coordinates||[])}function pointList(ring,bounds){return ring.map(p=>{const q=new kakao.maps.LatLng(p[1],p[0]);bounds.extend(q);allBounds.extend(q);hasAny=true;return q})}data.features.forEach((f,idx)=>{const name=(f.properties&&(f.properties.adm_nm||f.properties.adm_name||f.properties.name))||('행정동 '+(idx+1));const bounds=new kakao.maps.LatLngBounds();const polygons=[];ringsOf(f.geometry).forEach(poly=>{const path=(poly||[]).map(r=>pointList(r,bounds));const polygon=new kakao.maps.Polygon({map,path,strokeWeight:2,strokeColor:'#2477F3',strokeOpacity:.82,fillColor:'#72B7FF',fillOpacity:.18});polygons.push(polygon);kakao.maps.event.addListener(polygon,'click',function(){if(selected)selected.forEach(p=>p.setOptions({fillColor:'#72B7FF',fillOpacity:.18,strokeWeight:2}));selected=polygons;selected.forEach(p=>p.setOptions({fillColor:'#2477F3',fillOpacity:.34,strokeWeight:3}));map.setBounds(bounds,36,36,36,36);window.ReactNativeWebView.postMessage(JSON.stringify({type:'boundary',name}));});});const center=bounds.getCenter();new kakao.maps.CustomOverlay({map,position:center,content:'<div class="label">'+name.split(' ').pop()+'</div>',yAnchor:.5});});if(hasAny)map.setBounds(allBounds,24,24,24,24);});</script></body></html>`; }

export default function PublicDataAssignmentScreen({ user, group, onBack }) {
  const [boundaries, setBoundaries] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [category, setCategory] = useState('tree'); const [dong, setDong] = useState(''); const [selectedIds, setSelectedIds] = useState([]); const [assignee, setAssignee] = useState('');
  useEffect(() => { let cancelled = false; (async () => { try { const admCode = group?.regionAdmCode || '21100'; const response = await fetch(`${API_BASE_URL}/api/sgis/boundaries?admCode=${encodeURIComponent(admCode)}`); const text = await response.text(); if (!response.ok) throw new Error(text || 'SGIS 조회 실패'); if (!cancelled) setBoundaries(JSON.parse(text)); } catch (e) { if (!cancelled) setError(e.message || '행정동 경계를 불러오지 못했습니다.'); } finally { if (!cancelled) setLoading(false); } })(); return () => { cancelled = true; }; }, [group?.regionAdmCode]);
  useEffect(() => { setSelectedIds([]); }, [category, dong]);
  const items = useMemo(() => dong ? mockItems(dong, category) : [], [dong, category]); const members = group?.members || [];
  const assign = () => { if (!selectedIds.length) return showAlert('항목 선택', '배정할 공공데이터를 선택하세요.'); if (!assignee) return showAlert('담당자 선택', '업무를 배정할 팀원을 선택하세요.'); showAlert('배정 틀 준비 완료', `${dong}의 ${selectedIds.length}건을 ${members.find((m) => String(m.userId) === assignee)?.name || '담당자'}에게 배정하도록 연결할 수 있습니다. 실제 공공데이터 API가 연결되면 저장됩니다.`); };
  return <View style={styles.container}><ScreenHeader title="공공데이터 배정" subtitle={`${group?.regionSido || '부산광역시'} ${group?.regionSigungu || '사하구'}`} onBack={onBack} /><ScrollView contentContainerStyle={styles.body} nestedScrollEnabled>
    <Text style={styles.guide}>시설 종류를 고른 뒤 지도에서 행정동을 누르세요.</Text>
    <View style={styles.categories}>{CATEGORIES.map((item) => <TouchableOpacity key={item.key} style={[styles.category, category === item.key && styles.categoryActive]} onPress={() => setCategory(item.key)}><Ionicons name={item.icon} size={19} color={category === item.key ? '#FFFFFF' : colors.primary} /><Text style={[styles.categoryText, category === item.key && styles.categoryTextActive]}>{item.label}</Text></TouchableOpacity>)}</View>
    <View style={styles.mapCard}>{loading ? <View style={styles.mapState}><ActivityIndicator color={colors.primary} /><Text style={styles.stateText}>SGIS 행정동 경계를 불러오는 중...</Text></View> : error ? <View style={styles.mapState}><Ionicons name="alert-circle-outline" size={25} color={colors.danger} /><Text style={styles.error}>{error}</Text></View> : !KAKAO_KEY ? <View style={styles.mapState}><Text style={styles.error}>카카오 JavaScript 키가 필요합니다.</Text></View> : <WebView style={styles.map} originWhitelist={['*']} source={{ html: mapHtml(boundaries) }} javaScriptEnabled onMessage={(event) => { try { const message = JSON.parse(event.nativeEvent.data); if (message.type === 'boundary') setDong(message.name.split(' ').pop()); } catch {} }} />}</View>
    {!dong ? <EmptyState icon="map-outline" title="행정동을 선택하세요" description="경계를 누르면 지도가 확대되고 데이터 선택 목록이 열립니다." /> : <View style={styles.panel}><View style={styles.panelHeader}><View><Text style={styles.dong}>{dong}</Text><Text style={styles.count}>{CATEGORIES.find((item) => item.key === category)?.label} 예시 {items.length}건</Text></View><TouchableOpacity onPress={() => setSelectedIds(selectedIds.length === items.length ? [] : items.map((item) => item.id))}><Text style={styles.selectAll}>{selectedIds.length === items.length ? '선택 해제' : '전체 선택'}</Text></TouchableOpacity></View>{items.map((item) => { const checked = selectedIds.includes(item.id); return <TouchableOpacity key={item.id} style={styles.dataRow} onPress={() => setSelectedIds((prev) => checked ? prev.filter((id) => id !== item.id) : [...prev, item.id])}><View style={[styles.checkbox, checked && styles.checkboxActive]}>{checked ? <Ionicons name="checkmark" size={14} color="#FFFFFF" /> : null}</View><View style={{ flex: 1 }}><Text style={styles.dataName}>{item.name}</Text><Text style={styles.dataAddress}>{item.address}</Text></View></TouchableOpacity>; })}<Text style={styles.assignLabel}>담당자</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.memberChips}>{members.map((member) => <TouchableOpacity key={member.userId} style={[styles.memberChip, assignee === String(member.userId) && styles.memberChipActive]} onPress={() => setAssignee(String(member.userId))}><Text style={[styles.memberChipText, assignee === String(member.userId) && styles.memberChipTextActive]}>{member.name || member.loginId}</Text></TouchableOpacity>)}</ScrollView><PrimaryButton title={`선택한 ${selectedIds.length}건 업무로 배정`} icon="person-add-outline" onPress={assign} disabled={!selectedIds.length || !assignee} /></View>}
  </ScrollView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, body: { padding: 16, gap: 12, paddingBottom: 34 }, guide: { color: colors.textSoft, fontSize: 11, lineHeight: 17 }, categories: { flexDirection: 'row', gap: 8 }, category: { flex: 1, minHeight: 64, borderRadius: radius.medium, borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', gap: 5 }, categoryActive: { backgroundColor: colors.primary, borderColor: colors.primary }, categoryText: { color: colors.primary, fontSize: 10, fontWeight: '900' }, categoryTextActive: { color: '#FFFFFF' }, mapCard: { height: 360, borderRadius: radius.large, overflow: 'hidden', borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surfaceMuted }, map: { flex: 1 }, mapState: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 10, padding: 24 }, stateText: { color: colors.textSoft, fontSize: 11 }, error: { color: colors.danger, fontSize: 11, textAlign: 'center' }, panel: { backgroundColor: colors.surface, borderRadius: radius.large, borderWidth: 1, borderColor: colors.line, padding: 16 }, panelHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }, dong: { color: colors.text, fontSize: 19, fontWeight: '900' }, count: { color: colors.textSoft, fontSize: 10, marginTop: 3 }, selectAll: { color: colors.primary, fontSize: 11, fontWeight: '900' }, dataRow: { minHeight: 60, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: 'row', alignItems: 'center', gap: 10 }, checkbox: { width: 24, height: 24, borderRadius: 8, borderWidth: 2, borderColor: '#B9C6BF', alignItems: 'center', justifyContent: 'center' }, checkboxActive: { backgroundColor: colors.primary, borderColor: colors.primary }, dataName: { color: colors.text, fontSize: 12, fontWeight: '900' }, dataAddress: { color: colors.textSoft, fontSize: 9, marginTop: 3 }, assignLabel: { color: colors.text, fontSize: 12, fontWeight: '900', marginTop: 14 }, memberChips: { gap: 7, paddingVertical: 10 }, memberChip: { paddingHorizontal: 13, paddingVertical: 9, borderRadius: 999, backgroundColor: colors.surfaceMuted }, memberChipActive: { backgroundColor: colors.primary }, memberChipText: { color: colors.textSoft, fontSize: 10, fontWeight: '800' }, memberChipTextActive: { color: '#FFFFFF' } });
