import React, { useState } from 'react';
import { Alert, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { showAlert } from '../components/CustomAlert';
import { PrimaryButton, ScreenHeader, SectionTitle } from '../components/ui';
import { colors, radius } from '../constants/design';

const API_BASE_URL = process.env.EXPO_PUBLIC_API_BASE_URL;
const REGIONS = ['부산광역시', '서울특별시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시', '제주특별자치도'];

export default function SettingsScreen({ user, activeGroup, onBack, onUpdatedUser, onDashboard, onLogout }) {
  const [workSido, setWorkSido] = useState(user?.workSido || '부산광역시'); const [open, setOpen] = useState(false); const [saving, setSaving] = useState(false);
  const save = async () => { try { setSaving(true); const response = await fetch(`${API_BASE_URL}/api/users/${user.userId}/work-region`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ workSido }) }); const text = await response.text(); if (!response.ok) throw new Error(text || '저장 실패'); const saved = text ? JSON.parse(text) : {}; onUpdatedUser?.({ ...user, ...saved, workSido }); showAlert('저장 완료', '근무지역을 변경했습니다.'); } catch (error) { showAlert('저장 실패', error.message || '근무지역을 저장하지 못했습니다.'); } finally { setSaving(false); } };
  const logout = () => Alert.alert('로그아웃', '현재 계정에서 로그아웃하시겠습니까?', [{ text: '취소', style: 'cancel' }, { text: '로그아웃', style: 'destructive', onPress: onLogout }]);
  return <View style={styles.container}><ScreenHeader title="설정" subtitle="계정과 근무지역을 관리합니다" onBack={onBack} /><ScrollView contentContainerStyle={styles.body}>
    <View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{String(user?.name || user?.loginId || '?').slice(0, 1)}</Text></View><View style={{ flex: 1 }}><Text style={styles.name}>{user?.name || user?.loginId}</Text><Text style={styles.loginId}>@{user?.loginId}</Text></View></View>
    <SectionTitle title="근무지역" />
    <View style={styles.card}><TouchableOpacity style={styles.regionRow} onPress={() => setOpen(true)}><View style={styles.itemIcon}><Ionicons name="location-outline" size={21} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.itemLabel}>기본 시·도</Text><Text style={styles.itemValue}>{workSido}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textFaint} /></TouchableOpacity><Text style={styles.help}>그룹의 실제 활동 구·군은 각 그룹 설정을 따릅니다.</Text><PrimaryButton title={saving ? '저장 중...' : '변경사항 저장'} onPress={save} disabled={saving || workSido === (user?.workSido || '부산광역시')} /></View>
    <SectionTitle title="업무 도구" />
    <TouchableOpacity style={styles.menuRow} onPress={onDashboard}><View style={styles.itemIcon}><Ionicons name="stats-chart-outline" size={21} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.itemValue}>외근 분석</Text><Text style={styles.itemLabel}>{activeGroup?.groupName || '현재 업무공간'} 현황 보기</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textFaint} /></TouchableOpacity>
    <TouchableOpacity style={[styles.menuRow, styles.logoutRow]} onPress={logout}><View style={[styles.itemIcon, styles.logoutIcon]}><Ionicons name="log-out-outline" size={21} color={colors.danger} /></View><Text style={styles.logoutText}>로그아웃</Text></TouchableOpacity>
  </ScrollView><Modal visible={open} transparent animationType="fade"><TouchableOpacity style={styles.backdrop} activeOpacity={1} onPress={() => setOpen(false)}><View style={styles.sheet}><Text style={styles.sheetTitle}>근무지역 선택</Text>{REGIONS.map((region) => <TouchableOpacity key={region} style={styles.option} onPress={() => { setWorkSido(region); setOpen(false); }}><Text style={[styles.optionText, workSido === region && styles.optionActive]}>{region}</Text>{workSido === region ? <Ionicons name="checkmark-circle" size={21} color={colors.primary} /> : null}</TouchableOpacity>)}</View></TouchableOpacity></Modal></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, body: { padding: 20, paddingBottom: 34 }, profile: { backgroundColor: colors.primaryDark, borderRadius: radius.large, padding: 18, flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 26 }, avatar: { width: 52, height: 52, borderRadius: 17, backgroundColor: '#CDE8DC', alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primaryDark, fontSize: 20, fontWeight: '900' }, name: { color: '#FFFFFF', fontSize: 18, fontWeight: '900' }, loginId: { color: '#CDE8DC', fontSize: 11, marginTop: 4 }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: radius.large, padding: 16, marginBottom: 26, gap: 13 }, regionRow: { flexDirection: 'row', alignItems: 'center', gap: 11 }, itemIcon: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, itemLabel: { color: colors.textSoft, fontSize: 10 }, itemValue: { color: colors.text, fontSize: 14, fontWeight: '900', marginTop: 3 }, help: { color: colors.textSoft, fontSize: 10, lineHeight: 16 }, menuRow: { minHeight: 68, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: radius.medium, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 10 }, logoutRow: { marginTop: 12 }, logoutIcon: { backgroundColor: colors.dangerSoft }, logoutText: { color: colors.danger, fontSize: 13, fontWeight: '900' }, backdrop: { flex: 1, backgroundColor: 'rgba(17,35,28,0.4)', justifyContent: 'center', padding: 24 }, sheet: { backgroundColor: colors.surface, borderRadius: radius.large, padding: 18 }, sheetTitle: { color: colors.text, fontSize: 18, fontWeight: '900', marginBottom: 8 }, option: { height: 48, borderTopWidth: 1, borderTopColor: colors.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, optionText: { color: colors.textSoft, fontSize: 13 }, optionActive: { color: colors.primary, fontWeight: '900' } });
