spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sahagu_fieldwork
    username: sahagu_admin
    password: sahagu_local_pw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

kakao:
  rest-api-key: c347aec2a50a9fb8cd52ba8c606a0553